2021-12-01 20:08:38.650317: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-01 20:08:44.297240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8109 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:1a:00.0, compute capability: 8.6
2021-12-01 20:08:44.299247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 8109 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:1b:00.0, compute capability: 8.6
2021-12-01 20:08:44.301042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 8109 MB memory:  -> device: 2, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:1c:00.0, compute capability: 8.6
2021-12-01 20:08:44.302827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 8109 MB memory:  -> device: 3, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:1d:00.0, compute capability: 8.6
2021-12-01 20:08:44.304531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:4 with 8109 MB memory:  -> device: 4, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:1e:00.0, compute capability: 8.6
2021-12-01 20:08:44.306172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:5 with 8109 MB memory:  -> device: 5, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:3d:00.0, compute capability: 8.6
2021-12-01 20:08:44.308036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:6 with 8109 MB memory:  -> device: 6, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:3e:00.0, compute capability: 8.6
2021-12-01 20:08:44.310026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:7 with 8109 MB memory:  -> device: 7, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:3f:00.0, compute capability: 8.6
2021-12-01 20:08:44.312023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:8 with 8109 MB memory:  -> device: 8, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:40:00.0, compute capability: 8.6
2021-12-01 20:08:44.314011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:9 with 8109 MB memory:  -> device: 9, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:41:00.0, compute capability: 8.6
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 10, 45)]          0
_________________________________________________________________
gru (GRU)                    (None, 10, 256)           232704
_________________________________________________________________
gru_1 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_2 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_3 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_4 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_5 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_6 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_7 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_8 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_9 (GRU)                  (None, 10, 256)           394752
_________________________________________________________________
gru_10 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_11 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_12 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_13 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_14 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_15 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_16 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_17 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_18 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
gru_19 (GRU)                 (None, 10, 256)           394752
_________________________________________________________________
dense (Dense)                (None, 10, 2)             514
=================================================================
Total params: 7,733,506
Trainable params: 7,733,506
Non-trainable params: 0
_________________________________________________________________
training in progress
2021-12-01 20:08:51.080135: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Traceback (most recent call last):
  File "dev.py", line 144, in <module>
    callbacks=[WandbCallback()],
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/wandb/integration/keras/keras.py", line 168, in new_v2
    return old_v2(*args, **kwargs)
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/keras/engine/training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/keras/engine/training.py:835 run_step  **
        outputs = model.train_step(data)
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/keras/engine/training.py:787 train_step
        y_pred = self(x, training=True)
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/keras/engine/base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /geoinfo_vol1/home/z/h/zhao2/mambaforge/envs/myenv/lib/python3.7/site-packages/keras/engine/input_spec.py:269 assert_input_compatibility
        ', found shape=' + display_shape(x.shape))
    ValueError: Input 0 is incompatible with layer model: expected shape=(None, 10, 45), found shape=(None, 1003520, 45)
Epoch 1/50