2021-11-27 18:38:54,715 INFO    MainThread:10198 [wandb_setup.py:_flush():71] setting env: {}
2021-11-27 18:38:54,715 INFO    MainThread:10198 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-27 18:38:54,715 INFO    MainThread:10198 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-27 18:38:54,716 INFO    MainThread:10198 [wandb_init.py:_log_setup():371] Logging user logs to /geoinfo_vol1/home/z/h/zhao2/vit-keras/wandb/run-20211127_183854-tyqnilrg/logs/debug.log
2021-11-27 18:38:54,716 INFO    MainThread:10198 [wandb_init.py:_log_setup():372] Logging internal logs to /geoinfo_vol1/home/z/h/zhao2/vit-keras/wandb/run-20211127_183854-tyqnilrg/logs/debug-internal.log
2021-11-27 18:38:54,716 INFO    MainThread:10198 [wandb_init.py:init():404] calling init triggers
2021-11-27 18:38:54,716 INFO    MainThread:10198 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-11-27 18:38:54,717 INFO    MainThread:10198 [wandb_init.py:init():449] starting backend
2021-11-27 18:38:54,717 INFO    MainThread:10198 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-27 18:38:54,754 INFO    MainThread:10198 [backend.py:ensure_launched():199] starting backend process...
2021-11-27 18:38:54,783 INFO    MainThread:10198 [backend.py:ensure_launched():205] started backend process with pid: 10333
2021-11-27 18:38:54,785 INFO    MainThread:10198 [wandb_init.py:init():458] backend started and connected
2021-11-27 18:38:54,787 INFO    MainThread:10198 [wandb_init.py:init():519] updated telemetry
2021-11-27 18:38:54,847 INFO    MainThread:10198 [wandb_init.py:init():549] communicating current version
2021-11-27 18:38:55,994 INFO    MainThread:10198 [wandb_init.py:init():554] got version response 
2021-11-27 18:38:55,995 INFO    MainThread:10198 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-27 18:38:56,262 INFO    MainThread:10198 [wandb_init.py:init():592] starting run threads in backend
2021-11-27 18:39:01,279 INFO    MainThread:10198 [wandb_run.py:_console_start():1816] atexit reg
2021-11-27 18:39:01,280 INFO    MainThread:10198 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-11-27 18:39:01,281 INFO    MainThread:10198 [wandb_run.py:_redirect():1695] Redirecting console.
2021-11-27 18:39:01,284 INFO    MainThread:10198 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-27 18:39:01,285 INFO    MainThread:10198 [wandb_init.py:init():619] run started, returning control to user process
2021-11-27 18:39:49,584 INFO    MainThread:10198 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 255
2021-11-27 18:39:49,585 INFO    MainThread:10198 [wandb_run.py:_restore():1758] restore
