2021-12-01 20:13:23,502 INFO    MainThread:17130 [wandb_setup.py:_flush():71] setting env: {}
2021-12-01 20:13:23,502 INFO    MainThread:17130 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-01 20:13:23,503 INFO    MainThread:17130 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-01 20:13:23,503 INFO    MainThread:17130 [wandb_init.py:_log_setup():371] Logging user logs to /geoinfo_vol1/home/z/h/zhao2/vit-keras/wandb/run-20211201_201323-nmota39t/logs/debug.log
2021-12-01 20:13:23,503 INFO    MainThread:17130 [wandb_init.py:_log_setup():372] Logging internal logs to /geoinfo_vol1/home/z/h/zhao2/vit-keras/wandb/run-20211201_201323-nmota39t/logs/debug-internal.log
2021-12-01 20:13:23,504 INFO    MainThread:17130 [wandb_init.py:init():404] calling init triggers
2021-12-01 20:13:23,504 INFO    MainThread:17130 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-12-01 20:13:23,504 INFO    MainThread:17130 [wandb_init.py:init():449] starting backend
2021-12-01 20:13:23,505 INFO    MainThread:17130 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-01 20:13:23,532 INFO    MainThread:17130 [backend.py:ensure_launched():199] starting backend process...
2021-12-01 20:13:23,553 INFO    MainThread:17130 [backend.py:ensure_launched():205] started backend process with pid: 17267
2021-12-01 20:13:23,555 INFO    MainThread:17130 [wandb_init.py:init():458] backend started and connected
2021-12-01 20:13:23,557 INFO    MainThread:17130 [wandb_init.py:init():519] updated telemetry
2021-12-01 20:13:23,605 INFO    MainThread:17130 [wandb_init.py:init():549] communicating current version
2021-12-01 20:13:24,826 INFO    MainThread:17130 [wandb_init.py:init():554] got version response 
2021-12-01 20:13:24,826 INFO    MainThread:17130 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-01 20:13:25,077 INFO    MainThread:17130 [wandb_init.py:init():592] starting run threads in backend
2021-12-01 20:13:29,982 INFO    MainThread:17130 [wandb_run.py:_console_start():1816] atexit reg
2021-12-01 20:13:29,983 INFO    MainThread:17130 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-12-01 20:13:29,985 INFO    MainThread:17130 [wandb_run.py:_redirect():1695] Redirecting console.
2021-12-01 20:13:29,990 INFO    MainThread:17130 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-01 20:13:29,990 INFO    MainThread:17130 [wandb_init.py:init():619] run started, returning control to user process
2021-12-01 20:14:11,145 INFO    MainThread:17130 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 255
2021-12-01 20:14:11,145 INFO    MainThread:17130 [wandb_run.py:_restore():1758] restore
