2021-11-27 18:37:33,859 INFO    MainThread:9526 [wandb_setup.py:_flush():71] setting env: {}
2021-11-27 18:37:33,860 INFO    MainThread:9526 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-27 18:37:33,860 INFO    MainThread:9526 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-27 18:37:33,860 INFO    MainThread:9526 [wandb_init.py:_log_setup():371] Logging user logs to /geoinfo_vol1/home/z/h/zhao2/vit-keras/wandb/run-20211127_183733-uahjzh1g/logs/debug.log
2021-11-27 18:37:33,860 INFO    MainThread:9526 [wandb_init.py:_log_setup():372] Logging internal logs to /geoinfo_vol1/home/z/h/zhao2/vit-keras/wandb/run-20211127_183733-uahjzh1g/logs/debug-internal.log
2021-11-27 18:37:33,860 INFO    MainThread:9526 [wandb_init.py:init():404] calling init triggers
2021-11-27 18:37:33,861 INFO    MainThread:9526 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-11-27 18:37:33,861 INFO    MainThread:9526 [wandb_init.py:init():449] starting backend
2021-11-27 18:37:33,861 INFO    MainThread:9526 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-27 18:37:33,887 INFO    MainThread:9526 [backend.py:ensure_launched():199] starting backend process...
2021-11-27 18:37:33,909 INFO    MainThread:9526 [backend.py:ensure_launched():205] started backend process with pid: 9661
2021-11-27 18:37:33,911 INFO    MainThread:9526 [wandb_init.py:init():458] backend started and connected
2021-11-27 18:37:33,912 INFO    MainThread:9526 [wandb_init.py:init():519] updated telemetry
2021-11-27 18:37:33,965 INFO    MainThread:9526 [wandb_init.py:init():549] communicating current version
2021-11-27 18:37:35,258 INFO    MainThread:9526 [wandb_init.py:init():554] got version response 
2021-11-27 18:37:35,259 INFO    MainThread:9526 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-27 18:37:35,501 INFO    MainThread:9526 [wandb_init.py:init():592] starting run threads in backend
2021-11-27 18:37:40,519 INFO    MainThread:9526 [wandb_run.py:_console_start():1816] atexit reg
2021-11-27 18:37:40,521 INFO    MainThread:9526 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-11-27 18:37:40,521 INFO    MainThread:9526 [wandb_run.py:_redirect():1695] Redirecting console.
2021-11-27 18:37:40,524 INFO    MainThread:9526 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-27 18:37:40,524 INFO    MainThread:9526 [wandb_init.py:init():619] run started, returning control to user process
2021-11-27 18:38:24,151 INFO    MainThread:9526 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 255
2021-11-27 18:38:24,151 INFO    MainThread:9526 [wandb_run.py:_restore():1758] restore
