2021-11-26 23:16:06,175 INFO    MainThread:59474 [wandb_setup.py:_flush():71] setting env: {}
2021-11-26 23:16:06,176 INFO    MainThread:59474 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-26 23:16:06,176 INFO    MainThread:59474 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-26 23:16:06,176 INFO    MainThread:59474 [wandb_init.py:_log_setup():371] Logging user logs to /geoinfo_vol1/home/z/h/zhao2/vit-keras/wandb/run-20211126_231606-b9u82yh6/logs/debug.log
2021-11-26 23:16:06,176 INFO    MainThread:59474 [wandb_init.py:_log_setup():372] Logging internal logs to /geoinfo_vol1/home/z/h/zhao2/vit-keras/wandb/run-20211126_231606-b9u82yh6/logs/debug-internal.log
2021-11-26 23:16:06,178 INFO    MainThread:59474 [wandb_init.py:init():404] calling init triggers
2021-11-26 23:16:06,178 INFO    MainThread:59474 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-11-26 23:16:06,179 INFO    MainThread:59474 [wandb_init.py:init():449] starting backend
2021-11-26 23:16:06,179 INFO    MainThread:59474 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-26 23:16:06,209 INFO    MainThread:59474 [backend.py:ensure_launched():199] starting backend process...
2021-11-26 23:16:06,234 INFO    MainThread:59474 [backend.py:ensure_launched():205] started backend process with pid: 59627
2021-11-26 23:16:06,236 INFO    MainThread:59474 [wandb_init.py:init():458] backend started and connected
2021-11-26 23:16:06,238 INFO    MainThread:59474 [wandb_init.py:init():519] updated telemetry
2021-11-26 23:16:06,298 INFO    MainThread:59474 [wandb_init.py:init():549] communicating current version
2021-11-26 23:16:07,414 INFO    MainThread:59474 [wandb_init.py:init():554] got version response 
2021-11-26 23:16:07,414 INFO    MainThread:59474 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-26 23:16:07,671 INFO    MainThread:59474 [wandb_init.py:init():592] starting run threads in backend
2021-11-26 23:16:12,691 INFO    MainThread:59474 [wandb_run.py:_console_start():1816] atexit reg
2021-11-26 23:16:12,693 INFO    MainThread:59474 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-11-26 23:16:12,694 INFO    MainThread:59474 [wandb_run.py:_redirect():1695] Redirecting console.
2021-11-26 23:16:12,697 INFO    MainThread:59474 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-26 23:16:12,697 INFO    MainThread:59474 [wandb_init.py:init():619] run started, returning control to user process
2021-11-26 23:16:46,590 INFO    MainThread:59474 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-11-26 23:16:46,591 INFO    MainThread:59474 [wandb_run.py:_restore():1758] restore
2021-11-26 23:16:49,272 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2021-11-26 23:16:49,411 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2021-11-26 23:16:49,656 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2021-11-26 23:16:49,894 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 160321
}

2021-11-26 23:16:49,997 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,100 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,203 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,307 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,410 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,528 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,631 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,734 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,835 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:50,937 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:51,038 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:51,139 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:51,241 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 162970
}

2021-11-26 23:16:51,342 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3781
  total_bytes: 162970
}

2021-11-26 23:16:51,444 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:51,545 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:51,648 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:51,750 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:51,852 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:51,954 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:52,056 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:52,158 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:52,409 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}

2021-11-26 23:16:52,948 INFO    MainThread:59474 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 162970
  total_bytes: 162970
}
local_info {
}

2021-11-26 23:16:54,985 INFO    MainThread:59474 [wandb_run.py:_append_files():2184] logging synced files
